import {
  Activity,
  Archive,
  ArrowDownLeft,
  ArrowUpRight,
  Bell,
  Box,
  Building2,
  Calendar,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  Clock,
  Copy,
  Database,
  Download,
  Eye,
  FileText,
  Filter,
  History,
  Image as ImageIcon,
  Info,
  KeyRound,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Pencil,
  Play,
  Plus,
  Printer,
  QrCode,
  RefreshCw,
  ScanLine,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  Tag,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  Wrench,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/** Peta nama ikon (sama dengan mockup) → ikon lucide (pustaka ikon default shadcn/ui). */
export const ICONS = {
  dashboard: LayoutDashboard,
  box: Box,
  out: ArrowUpRight,
  in: ArrowDownLeft,
  activity: Activity,
  bell: Bell,
  file: FileText,
  database: Database,
  users: Users,
  user: User,
  shield: ShieldCheck,
  settings: Settings,
  search: Search,
  qr: QrCode,
  plus: Plus,
  download: Download,
  upload: Upload,
  clock: Clock,
  alert: TriangleAlert,
  check: Check,
  checkCircle: CircleCheck,
  mail: Mail,
  logout: LogOut,
  filter: Filter,
  printer: Printer,
  x: X,
  chev: ChevronRight,
  chevLeft: ChevronLeft,
  calendar: Calendar,
  image: ImageIcon,
  key: KeyRound,
  lock: Lock,
  pencil: Pencil,
  eye: Eye,
  refresh: RefreshCw,
  archive: Archive,
  server: Server,
  send: Send,
  scan: ScanLine,
  info: Info,
  menu: Menu,
  trash: Trash2,
  play: Play,
  tag: Tag,
  map: MapPin,
  building: Building2,
  camera: Camera,
  history: History,
  copy: Copy,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 18, ...rest }: { name: IconName; size?: number } & Omit<LucideProps, 'ref'>) {
  const C = ICONS[name];
  return <C size={size} strokeWidth={1.8} aria-hidden="true" {...rest} />;
}
