"""create_initial_schema_26_tables

Revision ID: f627cba678a2
Revises: 
Create Date: 2026-10-06 09:14:07.814336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f627cba678a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_table('locations',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], name=op.f('fk_locations_parent_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('code', name=op.f('uq_locations_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_locations_is_active'), 'locations', ['is_active'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_notification_templates_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notification_templates_is_active'), 'notification_templates', ['is_active'], unique=False)
    op.create_table('organizational_units',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('parent_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organizational_units.id'], name=op.f('fk_organizational_units_parent_id_organizational_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizational_units')),
    sa.UniqueConstraint('code', name=op.f('uq_organizational_units_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_organizational_units_is_active'), 'organizational_units', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizational_units_parent_id'), 'organizational_units', ['parent_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.create_table('assets',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('inventory_code', sa.String(length=50), nullable=False),
    sa.Column('category_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('location_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('owner_unit_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'TERSEDIA'"), nullable=False),
    sa.Column('condition', sa.String(length=30), server_default=sa.text("'BAIK'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.CheckConstraint("`condition` IN ('BAIK', 'RUSAK_RINGAN', 'RUSAK_BERAT')", name=op.f('ck_assets_condition')),
    sa.CheckConstraint("`status` IN ('TERSEDIA', 'DIPINJAM', 'RUSAK', 'RUSAK_BERAT', 'DALAM_PERBAIKAN', 'HILANG', 'NONAKTIF')", name=op.f('ck_assets_status')),
    sa.CheckConstraint('acquisition_cost IS NULL OR acquisition_cost >= 0', name=op.f('ck_assets_acquisition_cost_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_assets_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_assets_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_unit_id'], ['organizational_units.id'], name=op.f('fk_assets_owner_unit_id_organizational_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('inventory_code', name=op.f('uq_assets_inventory_code')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.create_index(op.f('ix_assets_condition'), 'assets', ['condition'], unique=False)
    op.create_index(op.f('ix_assets_is_active'), 'assets', ['is_active'], unique=False)
    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_owner_unit_id'), 'assets', ['owner_unit_id'], unique=False)
    op.create_index(op.f('ix_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('borrowers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('unit_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('identity_number', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['organizational_units.id'], name=op.f('fk_borrowers_unit_id_organizational_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borrowers')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_borrowers_email'), 'borrowers', ['email'], unique=False)
    op.create_index(op.f('ix_borrowers_identity_number'), 'borrowers', ['identity_number'], unique=False)
    op.create_index(op.f('ix_borrowers_is_active'), 'borrowers', ['is_active'], unique=False)
    op.create_index(op.f('ix_borrowers_name'), 'borrowers', ['name'], unique=False)
    op.create_index(op.f('ix_borrowers_unit_id'), 'borrowers', ['unit_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('permission_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_table('users',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('unit_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('deleted_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['organizational_units.id'], name=op.f('fk_users_unit_id_organizational_units'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_unit_id'), 'users', ['unit_id'], unique=False)
    op.create_table('asset_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('asset_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('changed_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('old_location_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('new_location_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('old_condition', sa.String(length=30), nullable=True),
    sa.Column('new_condition', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_history_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_asset_history_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['new_location_id'], ['locations.id'], name=op.f('fk_asset_history_new_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['old_location_id'], ['locations.id'], name=op.f('fk_asset_history_old_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_history')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_asset_history_asset_id_created_at', 'asset_history', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_asset_history_changed_by'), 'asset_history', ['changed_by'], unique=False)
    op.create_index('ix_asset_history_created_at', 'asset_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_asset_history_event_type'), 'asset_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_asset_history_new_location_id'), 'asset_history', ['new_location_id'], unique=False)
    op.create_index(op.f('ix_asset_history_old_location_id'), 'asset_history', ['old_location_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('borrowings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('borrower_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('handled_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('borrowed_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'AKTIF'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`status` IN ('AKTIF', 'TERLAMBAT', 'DIKEMBALIKAN', 'DIBATALKAN')", name=op.f('ck_borrowings_status')),
    sa.CheckConstraint('due_date >= start_date', name=op.f('ck_borrowings_due_date_after_start')),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_borrowings_borrower_id_borrowers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], name=op.f('fk_borrowings_handled_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borrowings')),
    sa.UniqueConstraint('transaction_number', name=op.f('uq_borrowings_transaction_number')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_borrowings_borrowed_at'), 'borrowings', ['borrowed_at'], unique=False)
    op.create_index(op.f('ix_borrowings_borrower_id'), 'borrowings', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_borrowings_due_date'), 'borrowings', ['due_date'], unique=False)
    op.create_index(op.f('ix_borrowings_handled_by'), 'borrowings', ['handled_by'], unique=False)
    op.create_index('ix_borrowings_status_due_date', 'borrowings', ['status', 'due_date'], unique=False)
    op.create_table('external_identities',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_external_identities_provider_provider_subject'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_external_identities_email'), 'external_identities', ['email'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_used_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), server_default=sa.text("'STRING'"), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`value_type` IN ('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'JSON')", name=op.f('ck_system_settings_value_type')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings')),
    sa.UniqueConstraint('key', name=op.f('uq_system_settings_key')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_system_settings_updated_by'), 'system_settings', ['updated_by'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('role_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('assigned_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('assigned_by', mysql.BIGINT(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_user_roles_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_roles_assigned_by'), 'user_roles', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_table('borrowing_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('borrowing_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('asset_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('checked_out_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_borrowing_items_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['borrowing_id'], ['borrowings.id'], name=op.f('fk_borrowing_items_borrowing_id_borrowings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_borrowing_items')),
    sa.UniqueConstraint('borrowing_id', 'asset_id', name='uq_borrowing_items_borrowing_id_asset_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_borrowing_items_asset_id'), 'borrowing_items', ['asset_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('borrowing_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('event_code', sa.String(length=50), nullable=False),
    sa.Column('scheduled_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('processed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`status` IN ('PENDING', 'PROCESSING', 'PROCESSED', 'SKIPPED', 'FAILED')", name=op.f('ck_notification_events_status')),
    sa.ForeignKeyConstraint(['borrowing_id'], ['borrowings.id'], name=op.f('fk_notification_events_borrowing_id_borrowings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_events')),
    sa.UniqueConstraint('borrowing_id', 'event_code', name='uq_notification_events_borrowing_id_event_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notification_events_status_scheduled_at', 'notification_events', ['status', 'scheduled_at'], unique=False)
    op.create_table('returns',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('borrowing_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('received_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('returned_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['borrowing_id'], ['borrowings.id'], name=op.f('fk_returns_borrowing_id_borrowings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], name=op.f('fk_returns_received_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_returns')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_returns_borrowing_id'), 'returns', ['borrowing_id'], unique=False)
    op.create_index(op.f('ix_returns_received_by'), 'returns', ['received_by'], unique=False)
    op.create_index(op.f('ix_returns_returned_at'), 'returns', ['returned_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('borrower_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('template_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('channel', sa.String(length=20), server_default=sa.text("'EMAIL'"), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_snapshot', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`channel` IN ('EMAIL')", name=op.f('ck_notifications_channel')),
    sa.CheckConstraint("`status` IN ('QUEUED', 'PROCESSING', 'SENT', 'FAILED', 'RETRYING')", name=op.f('ck_notifications_status')),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], name=op.f('fk_notifications_borrower_id_borrowers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_id'], ['notification_events.id'], name=op.f('fk_notifications_event_id_notification_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], name=op.f('fk_notifications_template_id_notification_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_notifications_borrower_id'), 'notifications', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_template_id'), 'notifications', ['template_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('return_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('borrowing_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('asset_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('final_condition', sa.String(length=20), nullable=False),
    sa.Column('completeness', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`final_condition` IN ('BAIK', 'RUSAK', 'HILANG')", name=op.f('ck_return_items_final_condition')),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_return_items_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['borrowing_item_id'], ['borrowing_items.id'], name=op.f('fk_return_items_borrowing_item_id_borrowing_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], name=op.f('fk_return_items_return_id_returns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_return_items')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_return_items_asset_id'), 'return_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_return_items_borrowing_item_id'), 'return_items', ['borrowing_item_id'], unique=False)
    op.create_index(op.f('ix_return_items_return_id'), 'return_items', ['return_id'], unique=False)
    op.create_table('damage_reports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('return_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('reported_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('repair_status', sa.String(length=30), server_default=sa.text("'DILAPORKAN'"), nullable=False),
    sa.Column('repair_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('reported_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('resolved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`repair_status` IN ('DILAPORKAN', 'DIPERIKSA', 'DALAM_PERBAIKAN', 'SELESAI', 'TIDAK_DAPAT_DIPERBAIKI')", name=op.f('ck_damage_reports_repair_status')),
    sa.CheckConstraint("`severity` IN ('RINGAN', 'SEDANG', 'BERAT')", name=op.f('ck_damage_reports_severity')),
    sa.CheckConstraint('repair_cost IS NULL OR repair_cost >= 0', name=op.f('ck_damage_reports_repair_cost_non_negative')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_damage_reports_reported_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], name=op.f('fk_damage_reports_return_item_id_return_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_damage_reports')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_damage_reports_repair_status'), 'damage_reports', ['repair_status'], unique=False)
    op.create_index(op.f('ix_damage_reports_reported_at'), 'damage_reports', ['reported_at'], unique=False)
    op.create_index(op.f('ix_damage_reports_reported_by'), 'damage_reports', ['reported_by'], unique=False)
    op.create_index(op.f('ix_damage_reports_return_item_id'), 'damage_reports', ['return_item_id'], unique=False)
    op.create_table('email_deliveries',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('notification_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('attempt_number', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('delivered_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.CheckConstraint("`status` IN ('PENDING', 'SENT', 'FAILED')", name=op.f('ck_email_deliveries_status')),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_email_deliveries_attempt_number_positive')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_email_deliveries_notification_id_notifications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_deliveries')),
    sa.UniqueConstraint('notification_id', 'attempt_number', name='uq_email_deliveries_notification_id_attempt_number'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_email_deliveries_attempted_at'), 'email_deliveries', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_email_deliveries_status'), 'email_deliveries', ['status'], unique=False)
    op.create_table('loss_reports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('return_item_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('reported_by', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_path', sa.String(length=500), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('reported_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('resolved_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_loss_reports_reported_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_item_id'], ['return_items.id'], name=op.f('fk_loss_reports_return_item_id_return_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loss_reports')),
    sa.UniqueConstraint('return_item_id', name=op.f('uq_loss_reports_return_item_id')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_loss_reports_reported_at'), 'loss_reports', ['reported_at'], unique=False)
    op.create_index(op.f('ix_loss_reports_reported_by'), 'loss_reports', ['reported_by'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('notification_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`status` IN ('QUEUED', 'PROCESSING', 'SENT', 'FAILED', 'RETRYING')", name=op.f('ck_notification_logs_status')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_logs_notification_id_notifications'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notification_logs_notification_id_created_at', 'notification_logs', ['notification_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index('ix_notification_logs_notification_id_created_at', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_loss_reports_reported_by'), table_name='loss_reports')
    op.drop_index(op.f('ix_loss_reports_reported_at'), table_name='loss_reports')
    op.drop_table('loss_reports')
    op.drop_index(op.f('ix_email_deliveries_status'), table_name='email_deliveries')
    op.drop_index(op.f('ix_email_deliveries_attempted_at'), table_name='email_deliveries')
    op.drop_table('email_deliveries')
    op.drop_index(op.f('ix_damage_reports_return_item_id'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_reported_by'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_reported_at'), table_name='damage_reports')
    op.drop_index(op.f('ix_damage_reports_repair_status'), table_name='damage_reports')
    op.drop_table('damage_reports')
    op.drop_index(op.f('ix_return_items_return_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_borrowing_item_id'), table_name='return_items')
    op.drop_index(op.f('ix_return_items_asset_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_notifications_template_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_borrower_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_returns_returned_at'), table_name='returns')
    op.drop_index(op.f('ix_returns_received_by'), table_name='returns')
    op.drop_index(op.f('ix_returns_borrowing_id'), table_name='returns')
    op.drop_table('returns')
    op.drop_index('ix_notification_events_status_scheduled_at', table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_borrowing_items_asset_id'), table_name='borrowing_items')
    op.drop_table('borrowing_items')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_assigned_by'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_system_settings_updated_by'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_email'), table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index('ix_borrowings_status_due_date', table_name='borrowings')
    op.drop_index(op.f('ix_borrowings_handled_by'), table_name='borrowings')
    op.drop_index(op.f('ix_borrowings_due_date'), table_name='borrowings')
    op.drop_index(op.f('ix_borrowings_borrower_id'), table_name='borrowings')
    op.drop_index(op.f('ix_borrowings_borrowed_at'), table_name='borrowings')
    op.drop_table('borrowings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_asset_history_old_location_id'), table_name='asset_history')
    op.drop_index(op.f('ix_asset_history_new_location_id'), table_name='asset_history')
    op.drop_index(op.f('ix_asset_history_event_type'), table_name='asset_history')
    op.drop_index('ix_asset_history_created_at', table_name='asset_history')
    op.drop_index(op.f('ix_asset_history_changed_by'), table_name='asset_history')
    op.drop_index('ix_asset_history_asset_id_created_at', table_name='asset_history')
    op.drop_table('asset_history')
    op.drop_index(op.f('ix_users_unit_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_borrowers_unit_id'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_name'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_is_active'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_identity_number'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_email'), table_name='borrowers')
    op.drop_table('borrowers')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_unit_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_is_active'), table_name='assets')
    op.drop_index(op.f('ix_assets_condition'), table_name='assets')
    op.drop_index(op.f('ix_assets_category_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizational_units_parent_id'), table_name='organizational_units')
    op.drop_index(op.f('ix_organizational_units_is_active'), table_name='organizational_units')
    op.drop_table('organizational_units')
    op.drop_index(op.f('ix_notification_templates_is_active'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_is_active'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
